# 데이터 분석 환경 설정과 넘파이 입문

## sckit-learn, 머신러닝 패키지 버전 설치하기
아나콘다 프롬프트에서 설치를 진행해야 한다. !를 제외한 명령어를 실행하면 된다.

In [9]:
!pip install scikit-learn==1.0.2

In [10]:
!conda install py-xgboost==1.5.0

Solving environment: ...working... done

# All requested packages already installed.

Retrieving notices: ...working... done


In [11]:
!conda install -c conda-forge lightgbm==3.3.2

^C


설치된 라이브러리의 버전을 확인한다.

In [1]:
import sklearn

sklearn.__version__

'1.0.2'

In [2]:
import xgboost

xgboost.__version__

C:\Users\isc03\anaconda3\lib\site-packages\xgboost\compat.py:36: FutureWarning: pandas.Int64Index is deprecated and will be removed from pandas in a future version. Use pandas.Index with the appropriate dtype instead.
  from pandas import MultiIndex, Int64Index


'1.5.0'

In [3]:
import lightgbm

lightgbm.__version__

'3.3.2'

# 넘파이
## 넘파이 배열 생성하기
numpy는 아나콘다 설치 시 기본으로 설치되어 있다.

In [4]:
import numpy as np # 별칭을 사용해서 임포트한다.

np의 기능을 활용해 배열을 생성한다.

In [5]:
arr0 = np.arange(0,10) # 파이썬의 range 와 기능이 유사하다.
arr0

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

arr0의 인덱스를 사용하면 데이터를 각각 추출해서 확인할 수 있다.

In [6]:
arr0[0]

0

In [7]:
arr0[-1]

9

In [8]:
arr0[5:7]

array([5, 6])

shape를 확인하면 현재 리스트가 어떤 모양으로 구성되었는지 확인할 수 있다.

In [9]:
arr0.shape # 행렬의 모양을 설명한다.

(10,)

기본 파이썬 리스트를 사용해서 ndarray을 생성할 수 있다.

In [10]:
# 리스트 생성
list0 = [1, 2, 3, 4, 5]
arr1 = np.array(list0) # 리스트를 ndarray로 변환해서 반환
arr1

array([1, 2, 3, 4, 5])

각 요소에 담은 데이터 형을 출력해보자.

In [11]:
arr1.dtype # 현재는 기본 설정으로 int32가 구성된다.

dtype('int32')

데이터 타입을 정하고 싶은 경우에는 int32나 int64와 같이 데이터형을 정해주는 것이 좋다.

In [12]:
arr2 = np.array(list0, dtype="int64")
arr2.dtype

dtype('int64')

## 2차원 배열 만들기

In [13]:
list1 = [[1, 2],
         [3, 4]] # 2차원 데이터 2x2

# 2차원 ndarray 구성하기
arr1 = np.array(list1)
arr1

array([[1, 2],
       [3, 4]])

In [14]:
arr1.shape

(2, 2)

2차원 배열도 인덱싱이 가능하다.

In [15]:
arr1[0] # 0번째 행을 가져옴

array([1, 2])

In [16]:
arr1[0][0] # 0번쨰 행에서 0번째 열을 가져온다.

1

In [17]:
arr1[0][1] # 0번쨰 행에서 1번째 열을 가져온다.

2

In [18]:
arr1[1][0] # 1번째 행에서 0번째 열을 가져온다.

3

In [19]:
arr1[1][1] # 1번째 행에서 1번째 열을 가져온다.

4

배열의 연산

In [20]:
arr1 + 2 # +2는 각각의 요소에 분배되어 연산된다.

array([[3, 4],
       [5, 6]])

In [21]:
arr1 * 2 # *2는 각각의 요소에 분배되어 연산된다.

array([[2, 4],
       [6, 8]])

2차원 배열 인덱싱

In [25]:
arr1[1:3] # 2번째 행을 반환하며 뒤에 내용이 없어도 오류는 없다. 1,2

array([[3, 4]])

In [28]:
arr1[1:2] # 1

array([[3, 4]])

In [26]:
arr1[0,1:] # 배열을 반환

array([2])

In [27]:
arr1[0,1] # 정확히 하나만 인덱싱하면 그 데이터가 나온다.

2

## 넘파이 비어있는 배열 생성하기
값을 초기화하지 않은 배열

In [29]:
np.empty([2,2])

array([[6.23042070e-307, 4.67296746e-307],
       [1.69121096e-306, 8.45606157e-307]])

값을 0으로 초기화한 배열

In [30]:
np.zeros([2,2])

array([[0., 0.],
       [0., 0.]])

In [31]:
np.zeros([2,2], dtype="int32")

array([[0, 0],
       [0, 0]])

## 랜덤한 배열 생성하기

In [32]:
np.random.randn(4,6) # 정규화된 랜덤 값을 리턴 

array([[ 0.21827943, -0.04595795, -1.39059641, -0.19313528,  2.78106248,
        -0.71637128],
       [-0.59036992, -1.40245047, -0.26960825,  0.97443089,  1.64306249,
        -0.38094676],
       [-0.10952019, -1.54461366, -1.61641559, -0.94838961, -0.75770153,
        -1.58303134],
       [ 1.73944857,  0.81562923, -0.5625429 , -0.59447634,  0.43586411,
        -0.42478941]])

In [38]:
np.random.randint(1,10, size=[10,22]) # 정수 범위 1~10, 배열의 모양은 10,22

array([[7, 9, 6, 1, 9, 9, 1, 3, 5, 6, 5, 9, 6, 6, 1, 8, 3, 7, 2, 1, 9, 4],
       [1, 2, 9, 3, 8, 5, 3, 2, 2, 4, 3, 7, 4, 1, 1, 3, 4, 9, 1, 1, 2, 5],
       [3, 8, 3, 2, 3, 1, 2, 6, 4, 6, 4, 6, 8, 9, 9, 2, 3, 1, 1, 2, 6, 2],
       [7, 4, 2, 1, 8, 2, 2, 4, 8, 6, 1, 7, 5, 4, 9, 2, 9, 5, 3, 9, 2, 3],
       [7, 4, 8, 9, 4, 4, 5, 9, 6, 5, 7, 1, 6, 3, 1, 5, 2, 8, 9, 5, 9, 7],
       [3, 1, 2, 1, 9, 6, 3, 6, 3, 1, 6, 3, 7, 3, 5, 1, 3, 1, 7, 2, 4, 5],
       [6, 6, 3, 2, 9, 4, 7, 9, 1, 7, 7, 8, 1, 2, 5, 3, 7, 7, 9, 3, 7, 4],
       [4, 4, 2, 1, 9, 2, 1, 3, 9, 5, 5, 5, 7, 3, 1, 2, 4, 6, 4, 6, 1, 6],
       [1, 4, 5, 8, 3, 2, 8, 7, 1, 6, 8, 3, 7, 8, 4, 9, 6, 9, 1, 3, 7, 3],
       [4, 5, 5, 5, 4, 6, 8, 8, 8, 6, 2, 3, 7, 9, 9, 5, 6, 8, 1, 8, 2, 3]])