# Pima Indians Diabetes Database

## 데이터 로드

In [9]:
import pandas as pd

df = pd.read_csv("diabetes.csv")
df.isnull().sum() # 비어있는 값 없음

Pregnancies                 0
Glucose                     0
BloodPressure               0
SkinThickness               0
Insulin                     0
BMI                         0
DiabetesPedigreeFunction    0
Age                         0
Outcome                     0
dtype: int64

In [10]:
y = df['Outcome'].values
y

array([1, 0, 1, 0, 1, 0, 1, 0, 1, 1, 0, 1, 0, 1, 1, 1, 1, 1, 0, 1, 0, 0,
       1, 1, 1, 1, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 1, 1, 0, 0, 0, 1,
       0, 1, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 1, 0,
       1, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0,
       1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1,
       1, 1, 0, 0, 1, 1, 1, 0, 0, 0, 1, 0, 0, 0, 1, 1, 0, 0, 1, 1, 1, 1,
       1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0,
       1, 1, 0, 0, 0, 1, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 1, 1, 0, 0, 0, 1,
       0, 1, 0, 1, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 0, 0, 1, 1, 0, 1, 0, 1,
       1, 1, 0, 0, 0, 0, 0, 0, 1, 1, 0, 1, 0, 0, 0, 1, 1, 1, 1, 0, 1, 1,
       1, 1, 0, 0, 0, 0, 0, 1, 0, 0, 1, 1, 0, 0, 0, 1, 1, 1, 1, 0, 0, 0,
       1, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 1, 0, 1, 0, 0,
       1, 0, 1, 0, 0, 1, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 1, 1, 0,
       0, 1, 0, 0, 0, 1, 1, 1, 0, 0, 1, 0, 1, 0, 1,

In [11]:
x = df.drop(['Outcome'], axis=1).values
x

array([[  6.   , 148.   ,  72.   , ...,  33.6  ,   0.627,  50.   ],
       [  1.   ,  85.   ,  66.   , ...,  26.6  ,   0.351,  31.   ],
       [  8.   , 183.   ,  64.   , ...,  23.3  ,   0.672,  32.   ],
       ...,
       [  5.   , 121.   ,  72.   , ...,  26.2  ,   0.245,  30.   ],
       [  1.   , 126.   ,  60.   , ...,  30.1  ,   0.349,  47.   ],
       [  1.   ,  93.   ,  70.   , ...,  30.4  ,   0.315,  23.   ]])

In [12]:
from sklearn.preprocessing import StandardScaler
scaler = StandardScaler()
scaler.fit(x)
x = scaler.transform(x)
x

array([[ 0.63994726,  0.84832379,  0.14964075, ...,  0.20401277,
         0.46849198,  1.4259954 ],
       [-0.84488505, -1.12339636, -0.16054575, ..., -0.68442195,
        -0.36506078, -0.19067191],
       [ 1.23388019,  1.94372388, -0.26394125, ..., -1.10325546,
         0.60439732, -0.10558415],
       ...,
       [ 0.3429808 ,  0.00330087,  0.14964075, ..., -0.73518964,
        -0.68519336, -0.27575966],
       [-0.84488505,  0.1597866 , -0.47073225, ..., -0.24020459,
        -0.37110101,  1.17073215],
       [-0.84488505, -0.8730192 ,  0.04624525, ..., -0.20212881,
        -0.47378505, -0.87137393]])

In [14]:
x.shape, y.shape

((768, 8), (768,))

In [15]:
len(x)

768

In [17]:
from sklearn.model_selection import train_test_split

train_x, test_x, train_y, test_y = train_test_split(x, y, test_size=0.2, random_state=0)

In [20]:
# 필요한 라이브러리 임포트
import numpy as np
import tensorflow as tf
import matplotlib.pyplot as plt
from sklearn.preprocessing import OneHotEncoder

# 시그모이드로 0~1사의 값을 최종 출력
def sigmoid(x):
    return 1 / (1 +np.exp(-x))

# 시그모이드 미분
def sigmoid_prime(z):
    return z * (1-z)


# 성능 이슈로 시그모이드가 아닌 relu 함수를 사용한다.
def relu(x):
    return np.maximum(0, x)


# 렐루의 미분 함수
def relu2deriv(output): 
    return output >= 0 

# 랜덤 시드
seed = 884736743
rng = np.random.default_rng(seed)

# 레이어에 필요한 변수 설정
learning_rate= 0.0005
epochs = 20
hidden_size= 4       # 히든 계층의 노드 개수
pixels_per_image = 8 # 입력 계층의 노드 개수
num_labels = 1

# 각 레이어에 필요한 가중치 설정
weights_1 = 0.2 * rng.random((pixels_per_image, hidden_size)) - 0.1 # 784x100
weights_2 = 0.2 * rng.random((hidden_size, num_labels)) - 0.1       # 100x10

# 학습 진행 현황을 기록할 저장소
store_training_loss = []
store_training_accurate_pred = []
store_test_loss = []
store_test_accurate_pred = []

# 루프 시작
for j in range(epochs):
    training_loss = 0.0
    training_accurate_predictions = 0
    
    for i in range(len(train_x)):
        # 포워드 패스
        layer_0 = train_x[i] # input
        layer_1 = relu(np.dot(layer_0, weights_1)) # l1
        layer_2 = sigmoid(np.dot(layer_1, weights_2)) # l2
        
        # 업데이트를 위해 오차 계산
        layer_2_delta = (train_y[i] - layer_2) * sigmoid_prime(layer_2) # 마지막 레이어의 Loss
        layer_1_delta = np.dot(weights_2, layer_2_delta) * relu2deriv(layer_1) # 한 레이어 전의 오류 계산
        
        # 변화할 가중치를 원래 가중치에 더함
        weights_1 += learning_rate * np.outer(layer_0, layer_1_delta)
        weights_2 += learning_rate * np.outer(layer_1, layer_2_delta)
        
    # 한번의 에포치가 종료될 때마다 평가 결과를 측정한다.
    results = sigmoid(relu(test_x @ weights_1) @ weights_2)
    test_loss = np.sum((test_y - results) ** 2 )/test_x.shape[0] # MSE
    results[results >= 0.5] = 1 
    results[results < 0.5] = 0
    test_accurate_predictions = np.sum(results == test_y)/test_x.shape[0]
    
    # 한번의 에포치가 종료될 때마다 훈련 결과를 측정한다.
    results = sigmoid(relu(train_x @ weights_1) @ weights_2)
    training_loss = np.sum((train_y - results) ** 2 ) / train_x.shape[0] # MSE
    results[results >= 0.5] = 1 
    results[results < 0.5] = 0
    training_accurate_predictions =  np.sum(results == train_y)/ train_x.shape[0]
    
    # 이번 에포치의 결과를 저장한다.
    store_training_loss.append(training_loss)
    store_training_accurate_pred.append(training_accurate_predictions)
    store_test_loss.append(test_loss)
    store_test_accurate_pred.append(test_accurate_predictions)
    
    # 이벤 에포치의 결과를 프린트
    print(f'''\
Epoch: {j} Training set error: {training_loss :.3f} \
Traing set accuracy: {training_accurate_predictions:.3f} \
Test set error: {test_loss:.3f} \
Test set accuracy: {test_accurate_predictions:.3f} \
''')        

Epoch: 0 Training set error: 153.341 Traing set accuracy: 325.208 Test set error: 38.439 Test set accuracy: 82.455 
Epoch: 1 Training set error: 153.335 Traing set accuracy: 324.368 Test set error: 38.436 Test set accuracy: 81.675 
Epoch: 2 Training set error: 153.328 Traing set accuracy: 323.808 Test set error: 38.433 Test set accuracy: 81.675 
Epoch: 3 Training set error: 153.321 Traing set accuracy: 323.248 Test set error: 38.431 Test set accuracy: 82.065 
Epoch: 4 Training set error: 153.314 Traing set accuracy: 322.687 Test set error: 38.428 Test set accuracy: 82.065 
Epoch: 5 Training set error: 153.306 Traing set accuracy: 322.407 Test set error: 38.424 Test set accuracy: 81.286 
Epoch: 6 Training set error: 153.298 Traing set accuracy: 322.127 Test set error: 38.421 Test set accuracy: 80.896 
Epoch: 7 Training set error: 153.290 Traing set accuracy: 322.127 Test set error: 38.418 Test set accuracy: 80.896 
Epoch: 8 Training set error: 153.281 Traing set accuracy: 322.127 Test s

In [29]:
results

array([[1.],
       [0.],
       [1.],
       [0.],
       [1.],
       [0.],
       [1.],
       [1.],
       [0.],
       [0.],
       [1.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [1.],
       [0.],
       [0.],
       [1.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [1.],
       [0.],
       [1.],
       [1.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [1.],
       [0.],
       [0.],
       [0.],
       [0.],
       [1.],
       [1.],
       [1.],
       [0.],
       [0.],
       [0.],
       [0.],
       [1.],
       [1.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [1.],
       [0.],
       [0.],
       [0.],
       [1.],
       [0.],
       [1.],
       [0.],
       [0.],
       [0.],
       [1.],
       [1.],
       [0.],
       [1.],
       [1.],
       [1.],
       [0.],
       [0.],
       [1.],

array([-58301.42194996,  20150.72168485, 138197.56431453,  34957.20337142,
       -71090.59059184,  35581.74002362,  17687.38307972, -51500.23347254])