# 파이토치 텐서 

필요한 라이브러리 임포트

In [1]:
import torch
import numpy as np

## 배열 생성하기
리스트나 넘파이 배열로부터 텐서 생성하기

In [4]:
data = [[1,2], [3,4]]
x_data = torch.tensor(data)
x_data

tensor([[1, 2],
        [3, 4]])

In [5]:
np_array = np.array(data)
x_np = torch.from_numpy(np_array) 
x_np

tensor([[1, 2],
        [3, 4]], dtype=torch.int32)

이미 선언된 텐서의 모양을 사용해 새로운 텐서 만들기

In [6]:
x_ones = torch.ones_like(x_data)
x_ones # 1로 채운 데이터

tensor([[1, 1],
        [1, 1]])

In [8]:
x_rand = torch.rand_like(x_data, dtype=torch.float)
x_rand # 랜덤으로 채운 데이터

tensor([[0.0261, 0.5401],
        [0.2447, 0.0942]])

모양을 선언해서 텐서 만들기

In [9]:
shape = (2,3)
rand_tensor = torch.rand(shape)
ones_tensor = torch.ones(shape)
zeros_tensor = torch.zeros(shape)

rand_tensor, ones_tensor, zeros_tensor

(tensor([[0.8098, 0.4554, 0.9781],
         [0.8564, 0.9337, 0.0785]]),
 tensor([[1., 1., 1.],
         [1., 1., 1.]]),
 tensor([[0., 0., 0.],
         [0., 0., 0.]]))

## 텐서의 속성
텐서의 속성은 넘파이와 유사하다.

In [10]:
print(f'텐서의 모양: {rand_tensor.shape}')
print(f'텐서의 데이터타입: {rand_tensor.dtype}')
print(f'텐서의 저장 위치: {rand_tensor.device}')

텐서의 모양: torch.Size([2, 3])
텐서의 데이터타입: torch.float32
텐서의 저장 위치: cpu


In [11]:
if torch.cuda.is_available():
    rand_tensor = rand_tensor.to('cuda')

## 텐서 인덱싱하기

인덱싱하기

In [14]:
tensor = torch.rand(4,4)
tensor

tensor([[0.7679, 0.8059, 0.4540, 0.0241],
        [0.8200, 0.9407, 0.1871, 0.4521],
        [0.0504, 0.4232, 0.1339, 0.6958],
        [0.8049, 0.2667, 0.5386, 0.1615]])

In [15]:
tensor[0] # 첫 번째 행

tensor([0.7679, 0.8059, 0.4540, 0.0241])

In [16]:
tensor[:,0] # 첫 번째 열

tensor([0.7679, 0.8200, 0.0504, 0.8049])

In [17]:
tensor[1,1] # 첫 번째 행의 첫 번째 열

tensor(0.9407)

In [18]:
tensor[:,1] = 0 # 데이터를 조회해서 입력
tensor

tensor([[0.7679, 0.0000, 0.4540, 0.0241],
        [0.8200, 0.0000, 0.1871, 0.4521],
        [0.0504, 0.0000, 0.1339, 0.6958],
        [0.8049, 0.0000, 0.5386, 0.1615]])

## 배열 합치기 

In [21]:
torch.cat([tensor, tensor, tensor], dim=1) # 옆으로 합치기

tensor([[0.7679, 0.0000, 0.4540, 0.0241, 0.7679, 0.0000, 0.4540, 0.0241, 0.7679,
         0.0000, 0.4540, 0.0241],
        [0.8200, 0.0000, 0.1871, 0.4521, 0.8200, 0.0000, 0.1871, 0.4521, 0.8200,
         0.0000, 0.1871, 0.4521],
        [0.0504, 0.0000, 0.1339, 0.6958, 0.0504, 0.0000, 0.1339, 0.6958, 0.0504,
         0.0000, 0.1339, 0.6958],
        [0.8049, 0.0000, 0.5386, 0.1615, 0.8049, 0.0000, 0.5386, 0.1615, 0.8049,
         0.0000, 0.5386, 0.1615]])

In [22]:
torch.cat([tensor, tensor, tensor], dim=0) # 위아래로 합치기

tensor([[0.7679, 0.0000, 0.4540, 0.0241],
        [0.8200, 0.0000, 0.1871, 0.4521],
        [0.0504, 0.0000, 0.1339, 0.6958],
        [0.8049, 0.0000, 0.5386, 0.1615],
        [0.7679, 0.0000, 0.4540, 0.0241],
        [0.8200, 0.0000, 0.1871, 0.4521],
        [0.0504, 0.0000, 0.1339, 0.6958],
        [0.8049, 0.0000, 0.5386, 0.1615],
        [0.7679, 0.0000, 0.4540, 0.0241],
        [0.8200, 0.0000, 0.1871, 0.4521],
        [0.0504, 0.0000, 0.1339, 0.6958],
        [0.8049, 0.0000, 0.5386, 0.1615]])

## 산술 연산
행렬의 곱

In [24]:
tensor @ tensor.T # matmul<- dot

tensor([[0.7964, 0.7255, 0.1163, 0.8665],
        [0.7255, 0.9118, 0.3809, 0.8338],
        [0.1163, 0.3809, 0.5046, 0.2251],
        [0.8665, 0.8338, 0.2251, 0.9641]])

In [26]:
tensor.matmul(tensor.T) 

tensor([[0.7964, 0.7255, 0.1163, 0.8665],
        [0.7255, 0.9118, 0.3809, 0.8338],
        [0.1163, 0.3809, 0.5046, 0.2251],
        [0.8665, 0.8338, 0.2251, 0.9641]])

In [29]:
y3 = torch.zeros(4,4)
torch.matmul(tensor, tensor.T, out=y3) 
y3

tensor([[0.7964, 0.7255, 0.1163, 0.8665],
        [0.7255, 0.9118, 0.3809, 0.8338],
        [0.1163, 0.3809, 0.5046, 0.2251],
        [0.8665, 0.8338, 0.2251, 0.9641]])

아마다르 곱

In [32]:
tensor * tensor # 모양이 같아야 함

tensor([[5.8968e-01, 0.0000e+00, 2.0613e-01, 5.8007e-04],
        [6.7243e-01, 0.0000e+00, 3.5011e-02, 2.0436e-01],
        [2.5408e-03, 0.0000e+00, 1.7929e-02, 4.8409e-01],
        [6.4786e-01, 0.0000e+00, 2.9013e-01, 2.6090e-02]])

In [33]:
tensor.mul(tensor)

tensor([[5.8968e-01, 0.0000e+00, 2.0613e-01, 5.8007e-04],
        [6.7243e-01, 0.0000e+00, 3.5011e-02, 2.0436e-01],
        [2.5408e-03, 0.0000e+00, 1.7929e-02, 4.8409e-01],
        [6.4786e-01, 0.0000e+00, 2.9013e-01, 2.6090e-02]])

In [34]:
y3 = torch.zeros(4,4)
torch.mul(tensor, tensor, out=y3) 
y3

tensor([[5.8968e-01, 0.0000e+00, 2.0613e-01, 5.8007e-04],
        [6.7243e-01, 0.0000e+00, 3.5011e-02, 2.0436e-01],
        [2.5408e-03, 0.0000e+00, 1.7929e-02, 4.8409e-01],
        [6.4786e-01, 0.0000e+00, 2.9013e-01, 2.6090e-02]])

집계 함수

In [38]:
agg = tensor.sum() # tensor 로 출력
agg.item() # tensor의 정보를 출력

5.09031867980957

브로드캐스트

In [40]:
tensor + 5

tensor([[5.7679, 5.0000, 5.4540, 5.0241],
        [5.8200, 5.0000, 5.1871, 5.4521],
        [5.0504, 5.0000, 5.1339, 5.6958],
        [5.8049, 5.0000, 5.5386, 5.1615]])

In [41]:
tensor.add_(5)
tensor

tensor([[5.7679, 5.0000, 5.4540, 5.0241],
        [5.8200, 5.0000, 5.1871, 5.4521],
        [5.0504, 5.0000, 5.1339, 5.6958],
        [5.8049, 5.0000, 5.5386, 5.1615]])

## 텐서와 넘파이의 관계

텐서를 넘파이로 변환하기

In [42]:
t = torch.ones(5)
n = t.numpy()
n

array([1., 1., 1., 1., 1.], dtype=float32)

In [43]:
t.add_(1) # 브로드캐스트 수행
n

array([2., 2., 2., 2., 2.], dtype=float32)

In [44]:
n[0] = 0
t

tensor([0., 2., 2., 2., 2.])