# 파이토치 텐서 

필요한 라이브러리 임포트

In [1]:
import torch
import numpy as np

## 배열 생성하기
리스트나 넘파이 배열로부터 텐서 생성하기

In [4]:
data = [[1,2], [3,4]]
x_data = torch.tensor(data)
x_data

tensor([[1, 2],
        [3, 4]])

In [5]:
np_array = np.array(data)
x_np = torch.from_numpy(np_array) 
x_np

tensor([[1, 2],
        [3, 4]], dtype=torch.int32)

이미 선언된 텐서의 모양을 사용해 새로운 텐서 만들기

In [6]:
x_ones = torch.ones_like(x_data)
x_ones # 1로 채운 데이터

tensor([[1, 1],
        [1, 1]])

In [8]:
x_rand = torch.rand_like(x_data, dtype=torch.float)
x_rand # 랜덤으로 채운 데이터

tensor([[0.0261, 0.5401],
        [0.2447, 0.0942]])

모양을 선언해서 텐서 만들기

In [9]:
shape = (2,3)
rand_tensor = torch.rand(shape)
ones_tensor = torch.ones(shape)
zeros_tensor = torch.zeros(shape)

rand_tensor, ones_tensor, zeros_tensor

(tensor([[0.8098, 0.4554, 0.9781],
         [0.8564, 0.9337, 0.0785]]),
 tensor([[1., 1., 1.],
         [1., 1., 1.]]),
 tensor([[0., 0., 0.],
         [0., 0., 0.]]))

## 텐서의 속성
텐서의 속성은 넘파이와 유사하다.

In [10]:
print(f'텐서의 모양: {rand_tensor.shape}')
print(f'텐서의 데이터타입: {rand_tensor.dtype}')
print(f'텐서의 저장 위치: {rand_tensor.device}')

텐서의 모양: torch.Size([2, 3])
텐서의 데이터타입: torch.float32
텐서의 저장 위치: cpu


In [11]:
if torch.cuda.is_available():
    rand_tensor = rand_tensor.to('cuda')

## 텐서 인덱싱하기

인덱싱하기

In [14]:
tensor = torch.rand(4,4)
tensor

tensor([[0.7679, 0.8059, 0.4540, 0.0241],
        [0.8200, 0.9407, 0.1871, 0.4521],
        [0.0504, 0.4232, 0.1339, 0.6958],
        [0.8049, 0.2667, 0.5386, 0.1615]])

In [15]:
tensor[0] # 첫 번째 행

tensor([0.7679, 0.8059, 0.4540, 0.0241])

In [16]:
tensor[:,0] # 첫 번째 열

tensor([0.7679, 0.8200, 0.0504, 0.8049])

In [17]:
tensor[1,1] # 첫 번째 행의 첫 번째 열

tensor(0.9407)

In [18]:
tensor[:,1] = 0 
tensor

tensor([[0.7679, 0.0000, 0.4540, 0.0241],
        [0.8200, 0.0000, 0.1871, 0.4521],
        [0.0504, 0.0000, 0.1339, 0.6958],
        [0.8049, 0.0000, 0.5386, 0.1615]])

## 배열 합치기 

In [21]:
torch.cat([tensor, tensor, tensor], dim=1) # 옆으로 합치기

tensor([[0.7679, 0.0000, 0.4540, 0.0241, 0.7679, 0.0000, 0.4540, 0.0241, 0.7679,
         0.0000, 0.4540, 0.0241],
        [0.8200, 0.0000, 0.1871, 0.4521, 0.8200, 0.0000, 0.1871, 0.4521, 0.8200,
         0.0000, 0.1871, 0.4521],
        [0.0504, 0.0000, 0.1339, 0.6958, 0.0504, 0.0000, 0.1339, 0.6958, 0.0504,
         0.0000, 0.1339, 0.6958],
        [0.8049, 0.0000, 0.5386, 0.1615, 0.8049, 0.0000, 0.5386, 0.1615, 0.8049,
         0.0000, 0.5386, 0.1615]])

In [22]:
torch.cat([tensor, tensor, tensor], dim=0) # 위아래로 합치기

tensor([[0.7679, 0.0000, 0.4540, 0.0241],
        [0.8200, 0.0000, 0.1871, 0.4521],
        [0.0504, 0.0000, 0.1339, 0.6958],
        [0.8049, 0.0000, 0.5386, 0.1615],
        [0.7679, 0.0000, 0.4540, 0.0241],
        [0.8200, 0.0000, 0.1871, 0.4521],
        [0.0504, 0.0000, 0.1339, 0.6958],
        [0.8049, 0.0000, 0.5386, 0.1615],
        [0.7679, 0.0000, 0.4540, 0.0241],
        [0.8200, 0.0000, 0.1871, 0.4521],
        [0.0504, 0.0000, 0.1339, 0.6958],
        [0.8049, 0.0000, 0.5386, 0.1615]])

## 산술 연산