# 트레이닝셋 테스트셋 분리하기

In [50]:
import numpy as np 
import pandas as pd

In [51]:
from sklearn import datasets

iris = datasets.load_iris()
x = iris['data']
y = iris['target']

columns = iris['feature_names'] + ['target']

iris_df = pd.DataFrame(np.hstack([x,y.reshape([-1,1])]), columns=columns)
iris_df

sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)  \
0                  5.1               3.5                1.4               0.2   
1                  4.9               3.0                1.4               0.2   
2                  4.7               3.2                1.3               0.2   
3                  4.6               3.1                1.5               0.2   
4                  5.0               3.6                1.4               0.2   
..                 ...               ...                ...               ...   
145                6.7               3.0                5.2               2.3   
146                6.3               2.5                5.0               1.9   
147                6.5               3.0                5.2               2.0   
148                6.2               3.4                5.4               2.3   
149                5.9               3.0                5.1               1.8   

     target  
0       0.0  
1       0.0  
2       0.0  
3       0.0  
4       0.0  
..      ...  
145     2.0  
146     2.0  
147     2.0  
148     2.0  
149     2.0  

[150 rows x 5 columns]

In [52]:
from sklearn.model_selection import train_test_split

x = iris_df.drop('target', axis=1).values
y = iris_df['target'].values # numpy로 변환해서 전달

train_x, test_x, train_y, test_y = train_test_split(x, y, test_size=0.2, random_state=123)

print(train_x.shape)
print(test_x.shape)
print(train_y.shape)
print(test_y.shape)

(120, 4)
(30, 4)
(120,)
(30,)


In [53]:
train_x[0], train_y[0]

(array([7.4, 2.8, 6.1, 1.9]), 2.0)

In [54]:
train_x[1], train_y[1]

(array([6. , 2.2, 5. , 1.5]), 2.0)

In [55]:
train_x[2], train_y[2]

(array([4.7, 3.2, 1.6, 0.2]), 0.0)

In [56]:
train_x[3], train_y[3]

(array([5.1, 3.5, 1.4, 0.2]), 0.0)

In [57]:
train_x[4], train_y[4]

(array([6. , 2.2, 4. , 1. ]), 1.0)

## 연습 문제
타이타닉 트레이닝 데이터를 가져와서 데이터셋을 나누어 학습용과 확인용으로 나누어 구성해보자.
- 데이터셋은 랜덤하게 구성되어야 한다.
- 데이터셋은 9:1 비율로 구성되어야 한다.



In [81]:
from sklearn.model_selection import train_test_split
import pandas as pd

titanic_df = pd.read_csv('titanic_train.csv')
titanic_df

PassengerId  Survived  Pclass  \
0              1         0       3   
1              2         1       1   
2              3         1       3   
3              4         1       1   
4              5         0       3   
..           ...       ...     ...   
886          887         0       2   
887          888         1       1   
888          889         0       3   
889          890         1       1   
890          891         0       3   

                                                  Name     Sex   Age  SibSp  \
0                              Braund, Mr. Owen Harris    male  22.0      1   
1    Cumings, Mrs. John Bradley (Florence Briggs Th...  female  38.0      1   
2                               Heikkinen, Miss. Laina  female  26.0      0   
3         Futrelle, Mrs. Jacques Heath (Lily May Peel)  female  35.0      1   
4                             Allen, Mr. William Henry    male  35.0      0   
..                                                 ...     ...   ...    ...   
886                              Montvila, Rev. Juozas    male  27.0      0   
887                       Graham, Miss. Margaret Edith  female  19.0      0   
888           Johnston, Miss. Catherine Helen "Carrie"  female   NaN      1   
889                              Behr, Mr. Karl Howell    male  26.0      0   
890                                Dooley, Mr. Patrick    male  32.0      0   

     Parch            Ticket     Fare Cabin Embarked  
0        0         A/5 21171   7.2500   NaN        S  
1        0          PC 17599  71.2833   C85        C  
2        0  STON/O2. 3101282   7.9250   NaN        S  
3        0            113803  53.1000  C123        S  
4        0            373450   8.0500   NaN        S  
..     ...               ...      ...   ...      ...  
886      0            211536  13.0000   NaN        S  
887      0            112053  30.0000   B42        S  
888      2        W./C. 6607  23.4500   NaN        S  
889      0            111369  30.0000  C148        C  
890      0            370376   7.7500   NaN        Q  

[891 rows x 12 columns]

In [82]:
# titanic 데이터에서 Survived를 제외한 값을 numpy array로 구성해서 x 담는다.
titanic_x = titanic_df.drop(['Survived'], axis=1).values
titanic_y = titanic_df['Survived'].values

tn_train_x, tn_test_x, tn_train_y, tn_tset_y = train_test_split(titanic_x, 
                                                                titanic_y, 
                                                                test_size=0.1, 
                                                                random_state=123)

print(tn_train_x.shape)
print(tn_test_x.shape)
print(tn_train_y.shape)
print(tn_tset_y.shape)

(801, 11)
(90, 11)
(801,)
(90,)


In [80]:
titanic_df.drop(['Survived'], axis=1)

PassengerId  Pclass                                               Name  \
0              1       3                            Braund, Mr. Owen Harris   
1              2       1  Cumings, Mrs. John Bradley (Florence Briggs Th...   
2              3       3                             Heikkinen, Miss. Laina   
3              4       1       Futrelle, Mrs. Jacques Heath (Lily May Peel)   
4              5       3                           Allen, Mr. William Henry   
..           ...     ...                                                ...   
886          887       2                              Montvila, Rev. Juozas   
887          888       1                       Graham, Miss. Margaret Edith   
888          889       3           Johnston, Miss. Catherine Helen "Carrie"   
889          890       1                              Behr, Mr. Karl Howell   
890          891       3                                Dooley, Mr. Patrick   

        Sex   Age  SibSp  Parch            Ticket     Fare Cabin Embarked  
0      male  22.0      1      0         A/5 21171   7.2500   NaN        S  
1    female  38.0      1      0          PC 17599  71.2833   C85        C  
2    female  26.0      0      0  STON/O2. 3101282   7.9250   NaN        S  
3    female  35.0      1      0            113803  53.1000  C123        S  
4      male  35.0      0      0            373450   8.0500   NaN        S  
..      ...   ...    ...    ...               ...      ...   ...      ...  
886    male  27.0      0      0            211536  13.0000   NaN        S  
887  female  19.0      0      0            112053  30.0000   B42        S  
888  female   NaN      1      2        W./C. 6607  23.4500   NaN        S  
889    male  26.0      0      0            111369  30.0000  C148        C  
890    male  32.0      0      0            370376   7.7500   NaN        Q  

[891 rows x 11 columns]

In [72]:
titanic_y.shape

(891,)

# 보스턴 집값 데이터셋
컬럼 목록 
- CRIM - per capita crime rate by town
- ZN - proportion of residential land zoned for lots over 25,000 sq.ft.
- INDUS - proportion of non-retail business acres per town.
- CHAS - Charles River dummy variable (1 if tract bounds river; 0 otherwise)
- NOX - nitric oxides concentration (parts per 10 million)
- RM - average number of rooms per dwelling
- AGE - proportion of owner-occupied units built prior to 1940
- DIS - weighted distances to five Boston employment centres
- RAD - index of accessibility to radial highways
- TAX - full-value property-tax rate per \$10,000
- PTRATIO - pupil-teacher ratio by town
- B - 1000(Bk - 0.63)^2 where Bk is the proportion of blacks by town
- LSTAT - % lower status of the population
- MEDV - Median value of owner-occupied homes in $1000's (y = MEDV)

8:2 트레인 테스트 셋으로 데이터를 분류하라.

In [1]:
import pandas as pd
import numpy as np 

In [10]:
columns = ['CRIM', 'ZN', 'INDUS', 'CHAS', 'NOX', 'RM', 'AGE', 'DIS', 
           'RAD', 'TAX', 'PTRATIO', 'B', 'LSTAT', 'MEDV']

# \s는 공백을, + 1자 이상을 의미해서 \s+는 공백 한 자 이상의 공백 기준으로 나누겠다는 의미다.
boston_df = pd.read_csv('housing.csv', sep='\s+', header=None, names=columns )
boston_df.head()

CRIM    ZN  INDUS  CHAS    NOX     RM   AGE     DIS  RAD    TAX  \
0  0.00632  18.0   2.31     0  0.538  6.575  65.2  4.0900    1  296.0   
1  0.02731   0.0   7.07     0  0.469  6.421  78.9  4.9671    2  242.0   
2  0.02729   0.0   7.07     0  0.469  7.185  61.1  4.9671    2  242.0   
3  0.03237   0.0   2.18     0  0.458  6.998  45.8  6.0622    3  222.0   
4  0.06905   0.0   2.18     0  0.458  7.147  54.2  6.0622    3  222.0   

   PTRATIO       B  LSTAT  MEDV  
0     15.3  396.90   4.98  24.0  
1     17.8  396.90   9.14  21.6  
2     17.8  392.83   4.03  34.7  
3     18.7  394.63   2.94  33.4  
4     18.7  396.90   5.33  36.2

In [16]:
from sklearn.model_selection import train_test_split

x = boston_df.drop(['MEDV'], axis=1).values
y = boston_df['MEDV'].values

boston_train_x, boston_test_x, boston_train_y, boston_test_y= train_test_split(x, y, 
                                                                               test_size=0.2, 
                                                                               random_state=1234)

In [17]:
print(boston_train_x.shape)
print(boston_test_x.shape)
print(boston_train_y.shape)
print(boston_test_y.shape)

(404, 13)
(102, 13)
(404,)
(102,)


In [18]:
boston_train_y.shape[0]/boston_test_y.shape[0]

3.9607843137254903