# 넘파이 기본

## Numpy 배열 생성 – 연습문제
1. 다음과 같은 2x3 배열을 만들어보세요

  array([[0,1,2],
  
     [0,1,2]])

2. 다음과 같은 3의 배수를 가진 3x3 배열을 만들어보세요

array([[ 0,  3,  6],

      [ 9, 12, 15],

      [18, 21, 24]])

In [2]:
list0 = [0,1,2] # 이 리스트를 기본으로 시작해서 위에 ndarray를 구성하시오

In [5]:
import numpy as np

# 1
arr0 = np.array([list0,
                 list0])

print("행렬:", arr0.shape)
arr0

행렬: (2, 3)


array([[0, 1, 2],
       [0, 1, 2]])

In [9]:
# 2
temp_array = np.array(list0) * 3
temp_array

array([0, 3, 6])

In [12]:
arr1 = np.array([temp_array,
                 temp_array + 9,
                 temp_array + 18])

print("행렬:", arr1.shape)
arr1

행렬: (3, 3)


array([[ 0,  3,  6],
       [ 9, 12, 15],
       [18, 21, 24]])

In [13]:
(3,3)

(3, 3)

In [14]:
type(arr1)

numpy.ndarray

In [15]:
type( arr1.shape)

tuple

## ndarray의 속성들

In [19]:
arr2 = np.arange(15).reshape(3, 5) # 3x5의 배열로 arr2를 구성
arr2

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [23]:
print(f'''\
차원 수:        {arr2.ndim}
각 데이터의 크기:{arr2.itemsize}
데이터의 개수:   {arr2.size}
배열의 총 크기:  {arr2.nbytes}
배열의 모양:     {arr2.shape}
교차된 배열:     
{arr2.T}
''')

차원 수:        2
각 데이터의 크기:4
데이터의 개수:   15
배열의 총 크기:  60
배열의 모양:     (3, 5)
교차된 배열:     
[[ 0  5 10]
 [ 1  6 11]
 [ 2  7 12]
 [ 3  8 13]
 [ 4  9 14]]



## 마스킹
데이터를 생성하고 마스킹을 실습해보자.

In [26]:
data_array = np.random.randn(7,4)
data_array

array([[-1.25873294, -0.33729826,  0.7727157 , -1.86816001],
       [ 0.16392851, -0.03608855,  0.96418571, -0.68979284],
       [ 0.62276599,  1.33915308,  1.03047151,  0.53190202],
       [-0.28644738,  1.11632809, -0.26851017,  1.23621221],
       [-0.84667207, -1.27135422,  0.05953679, -1.886005  ],
       [ 0.19581216,  0.82089817,  2.65553162,  2.06459259],
       [-0.23081466, -0.5544223 ,  0.1177837 , -0.61153283]])

불린 마스크: 불린 타입으로 구성된 마스크를 생성한다.

In [24]:
mask = np.array([0,1,0,1,0,1,0], dtype="bool")
mask

array([False,  True, False,  True, False,  True, False])

마스크를 씌우면 참인 데이터만 필터링되어 나타난다. 불린 타입을 사용해 행의 데이터를 선택적으로 가져왔다.

In [27]:
data_array[mask]

array([[ 0.16392851, -0.03608855,  0.96418571, -0.68979284],
       [-0.28644738,  1.11632809, -0.26851017,  1.23621221],
       [ 0.19581216,  0.82089817,  2.65553162,  2.06459259]])

In [29]:
data_array[~mask]

array([[-1.25873294, -0.33729826,  0.7727157 , -1.86816001],
       [ 0.62276599,  1.33915308,  1.03047151,  0.53190202],
       [-0.84667207, -1.27135422,  0.05953679, -1.886005  ],
       [-0.23081466, -0.5544223 ,  0.1177837 , -0.61153283]])

펜시 인덱싱

In [32]:
data_array[[0,6]]

array([[-1.25873294, -0.33729826,  0.7727157 , -1.86816001],
       [-0.23081466, -0.5544223 ,  0.1177837 , -0.61153283]])

In [34]:
data_array[2:4]

array([[ 0.62276599,  1.33915308,  1.03047151,  0.53190202],
       [-0.28644738,  1.11632809, -0.26851017,  1.23621221]])

ndarray는 브로드캐스트로 연산되는 기능을 가지고 있다. 따라서 비교 연산자도 브로드캐스트된다.

In [40]:
boolean_mask = data_array > 0 # 0보다 큰지를 구별하는 불린 마스크
boolean_mask

array([[False, False,  True, False],
       [ True, False,  True, False],
       [ True,  True,  True,  True],
       [False,  True, False,  True],
       [False, False,  True, False],
       [ True,  True,  True,  True],
       [False, False,  True, False]])

In [41]:
data_array[boolean_mask]

array([0.7727157 , 0.16392851, 0.96418571, 0.62276599, 1.33915308,
       1.03047151, 0.53190202, 1.11632809, 1.23621221, 0.05953679,
       0.19581216, 0.82089817, 2.65553162, 2.06459259, 0.1177837 ])

In [42]:
# 앞서 차례로 수행한 작업을 한 번에 적으면 다음과 같아진다.
data_array[data_array > 0]

array([0.7727157 , 0.16392851, 0.96418571, 0.62276599, 1.33915308,
       1.03047151, 0.53190202, 1.11632809, 1.23621221, 0.05953679,
       0.19581216, 0.82089817, 2.65553162, 2.06459259, 0.1177837 ])

## 마스킹 연습 문제
1. 1~10까지 데이터를 무작위로 생성해 100개 짜리 배열을 생성하라.
2. 5x20의 형태로 배열을 정렬하라.
3. 데이터 형은 int64로 정의하라.
4. 5x20 배열에서 2,3행을 출력하라.
5. 5보다 큰 데이터를 필터링해서 출력하라.

In [57]:
# 1
import numpy as np

test_arr = np.random.randint(1, 10, size=100)

#2
test_arr = test_arr.reshape([5,20])

print("모양", test_arr.shape)

#3
test_arr = test_arr.astype('int64')

print("데이터형:", test_arr.dtype)

#4 
print("2~3행 출력:\n", test_arr[2:4])

#5
mask = test_arr>5
print("5보다 큰 데이터 출력:\n", test_arr[mask])

모양 (5, 20)
데이터형: int64
2~3행 출력:
 [[8 3 9 6 4 6 9 4 7 5 2 9 4 3 7 2 5 9 3 9]
 [3 9 9 4 7 1 6 9 2 2 7 4 9 2 4 1 3 5 2 5]]
5보다 큰 데이터 출력:
 [8 9 6 6 6 6 7 6 6 9 9 6 7 6 7 9 8 9 6 6 9 7 9 7 9 9 9 9 7 6 9 7 9 6 8 8 7
 8 9 6 7 8 9 8 8]


In [50]:
test_arr

array([[7, 3, 5, 2, 6, 6, 4, 9, 5, 2, 2, 8, 7, 2, 6, 2, 1, 3, 7, 5],
       [8, 9, 6, 3, 9, 6, 8, 7, 3, 9, 9, 3, 9, 8, 1, 4, 5, 9, 2, 2],
       [3, 2, 4, 1, 5, 8, 7, 5, 9, 9, 3, 2, 1, 3, 1, 5, 5, 3, 1, 7],
       [1, 7, 7, 2, 3, 7, 3, 5, 1, 3, 5, 4, 4, 4, 2, 7, 7, 8, 2, 3],
       [1, 4, 8, 5, 4, 4, 2, 9, 2, 6, 8, 8, 6, 7, 6, 2, 2, 3, 2, 8]],
      dtype=int64)

## 배열의 모양 조작
ravel, flatten은 원본을 손상시키지 않으면서 새로운 메모리 배열 쭉펴서 반환한다.

In [58]:
test_arr.ravel()

array([8, 9, 3, 5, 6, 1, 3, 3, 6, 6, 2, 2, 5, 6, 3, 7, 6, 6, 2, 9, 4, 9,
       6, 7, 5, 2, 6, 2, 7, 4, 3, 5, 3, 3, 2, 2, 9, 4, 1, 1, 8, 3, 9, 6,
       4, 6, 9, 4, 7, 5, 2, 9, 4, 3, 7, 2, 5, 9, 3, 9, 3, 9, 9, 4, 7, 1,
       6, 9, 2, 2, 7, 4, 9, 2, 4, 1, 3, 5, 2, 5, 6, 8, 8, 7, 8, 9, 2, 6,
       7, 2, 1, 2, 5, 5, 8, 9, 1, 4, 8, 8], dtype=int64)

In [59]:
test_arr.flatten()

array([8, 9, 3, 5, 6, 1, 3, 3, 6, 6, 2, 2, 5, 6, 3, 7, 6, 6, 2, 9, 4, 9,
       6, 7, 5, 2, 6, 2, 7, 4, 3, 5, 3, 3, 2, 2, 9, 4, 1, 1, 8, 3, 9, 6,
       4, 6, 9, 4, 7, 5, 2, 9, 4, 3, 7, 2, 5, 9, 3, 9, 3, 9, 9, 4, 7, 1,
       6, 9, 2, 2, 7, 4, 9, 2, 4, 1, 3, 5, 2, 5, 6, 8, 8, 7, 8, 9, 2, 6,
       7, 2, 1, 2, 5, 5, 8, 9, 1, 4, 8, 8], dtype=int64)

In [60]:
test_arr

array([[8, 9, 3, 5, 6, 1, 3, 3, 6, 6, 2, 2, 5, 6, 3, 7, 6, 6, 2, 9],
       [4, 9, 6, 7, 5, 2, 6, 2, 7, 4, 3, 5, 3, 3, 2, 2, 9, 4, 1, 1],
       [8, 3, 9, 6, 4, 6, 9, 4, 7, 5, 2, 9, 4, 3, 7, 2, 5, 9, 3, 9],
       [3, 9, 9, 4, 7, 1, 6, 9, 2, 2, 7, 4, 9, 2, 4, 1, 3, 5, 2, 5],
       [6, 8, 8, 7, 8, 9, 2, 6, 7, 2, 1, 2, 5, 5, 8, 9, 1, 4, 8, 8]],
      dtype=int64)

test_arr.shape는 test_arr의 배열 모양을 설명한다. 이 값을 변경하면 배열의 모양도 바뀐다.

In [61]:
test_arr.shape = (25,4)
test_arr

array([[8, 9, 3, 5],
       [6, 1, 3, 3],
       [6, 6, 2, 2],
       [5, 6, 3, 7],
       [6, 6, 2, 9],
       [4, 9, 6, 7],
       [5, 2, 6, 2],
       [7, 4, 3, 5],
       [3, 3, 2, 2],
       [9, 4, 1, 1],
       [8, 3, 9, 6],
       [4, 6, 9, 4],
       [7, 5, 2, 9],
       [4, 3, 7, 2],
       [5, 9, 3, 9],
       [3, 9, 9, 4],
       [7, 1, 6, 9],
       [2, 2, 7, 4],
       [9, 2, 4, 1],
       [3, 5, 2, 5],
       [6, 8, 8, 7],
       [8, 9, 2, 6],
       [7, 2, 1, 2],
       [5, 5, 8, 9],
       [1, 4, 8, 8]], dtype=int64)

In [64]:
test_arr.transpose() # test_arr.T 와 같은 기능

array([[8, 6, 6, 5, 6, 4, 5, 7, 3, 9, 8, 4, 7, 4, 5, 3, 7, 2, 9, 3, 6, 8,
        7, 5, 1],
       [9, 1, 6, 6, 6, 9, 2, 4, 3, 4, 3, 6, 5, 3, 9, 9, 1, 2, 2, 5, 8, 9,
        2, 5, 4],
       [3, 3, 2, 3, 2, 6, 6, 3, 2, 1, 9, 9, 2, 7, 3, 9, 6, 7, 4, 2, 8, 2,
        1, 8, 8],
       [5, 3, 2, 7, 9, 7, 2, 5, 2, 1, 6, 4, 9, 2, 9, 4, 9, 4, 1, 5, 7, 6,
        2, 9, 8]], dtype=int64)

In [66]:
test_arr.resize(5,20) # 원본을 바꾸는 기능

In [67]:
test_arr.reshape(5,20) # 원본은 그대로 두고 새로운 배열을 반환하는 방법

array([[8, 9, 3, 5, 6, 1, 3, 3, 6, 6, 2, 2, 5, 6, 3, 7, 6, 6, 2, 9],
       [4, 9, 6, 7, 5, 2, 6, 2, 7, 4, 3, 5, 3, 3, 2, 2, 9, 4, 1, 1],
       [8, 3, 9, 6, 4, 6, 9, 4, 7, 5, 2, 9, 4, 3, 7, 2, 5, 9, 3, 9],
       [3, 9, 9, 4, 7, 1, 6, 9, 2, 2, 7, 4, 9, 2, 4, 1, 3, 5, 2, 5],
       [6, 8, 8, 7, 8, 9, 2, 6, 7, 2, 1, 2, 5, 5, 8, 9, 1, 4, 8, 8]],
      dtype=int64)

## 배열쌓기
vstack: 수직 쌓기

In [69]:
arr1 = np.arange(8)
arr1 

array([0, 1, 2, 3, 4, 5, 6, 7])

In [71]:
np.vstack([arr1, arr1 * 3])

array([[ 0,  1,  2,  3,  4,  5,  6,  7],
       [ 0,  3,  6,  9, 12, 15, 18, 21]])

hstack: 수평 쌓기

In [72]:
np.hstack([arr1, arr1*2])

array([ 0,  1,  2,  3,  4,  5,  6,  7,  0,  2,  4,  6,  8, 10, 12, 14])

dstack: 깊게

In [77]:
np.dstack([arr1, arr1**2])

array([[[ 0,  0],
        [ 1,  1],
        [ 2,  4],
        [ 3,  9],
        [ 4, 16],
        [ 5, 25],
        [ 6, 36],
        [ 7, 49]]])

## 배열 쪼개기
hsplit

In [78]:
a = np.arange(9).reshape(3,3)
a

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [79]:
np.hsplit(a, 3)

[array([[0],
        [3],
        [6]]),
 array([[1],
        [4],
        [7]]),
 array([[2],
        [5],
        [8]])]

vsplit

In [80]:
np.vsplit(a, 3)

[array([[0, 1, 2]]), array([[3, 4, 5]]), array([[6, 7, 8]])]

dsplit

In [82]:
b = np.arange(27).reshape(3,3,3)
b

array([[[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8]],

       [[ 9, 10, 11],
        [12, 13, 14],
        [15, 16, 17]],

       [[18, 19, 20],
        [21, 22, 23],
        [24, 25, 26]]])

In [83]:
np.dsplit(b, 3)

[array([[[ 0],
         [ 3],
         [ 6]],
 
        [[ 9],
         [12],
         [15]],
 
        [[18],
         [21],
         [24]]]),
 array([[[ 1],
         [ 4],
         [ 7]],
 
        [[10],
         [13],
         [16]],
 
        [[19],
         [22],
         [25]]]),
 array([[[ 2],
         [ 5],
         [ 8]],
 
        [[11],
         [14],
         [17]],
 
        [[20],
         [23],
         [26]]])]

## 배열 쌀기와 쪼개기
1. iris 데이터셋 가져오기
2. 배열 쪼개기와 쌓기 함수를 사용하여 다음 문제를 해결해보자.
  - sepal length(cm)의 값과 petal length(cm)의 값을 추출하여 새로운 배열을 생성하라.
  - 3번과 5번 데이터를 추출하여 새로운 배열을 생성하라. 

In [84]:
from sklearn import datasets

iris = datasets.load_iris() # iris 데이터
irisdt = iris['data']
colum_names = iris['feature_names'] # 피쳐, 컬럼

colum_names # irisdt

['sepal length (cm)',
 'sepal width (cm)',
 'petal length (cm)',
 'petal width (cm)']

In [87]:
import pandas as pd
pd.DataFrame(irisdt, columns=colum_names)

sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)
0                  5.1               3.5                1.4               0.2
1                  4.9               3.0                1.4               0.2
2                  4.7               3.2                1.3               0.2
3                  4.6               3.1                1.5               0.2
4                  5.0               3.6                1.4               0.2
..                 ...               ...                ...               ...
145                6.7               3.0                5.2               2.3
146                6.3               2.5                5.0               1.9
147                6.5               3.0                5.2               2.0
148                6.2               3.4                5.4               2.3
149                5.9               3.0                5.1               1.8

[150 rows x 4 columns]

sepal length(cm)의 값과 petal length(cm)의 값을 추출하여 새로운 배열을 생성하라.

옆으로 4개로 쪼개서 0번 데이터와 2번데이터를 옆으로 붙여라.

In [ ]:
sepal_length, sepal_width, petal_length, petal_width = np.hsplit(irisdt,4)
np.hstack([sepal_length, petal_length])

3번과 5번 데이터를 추출하여 새로운 배열을 생성하라.

수직으로 150개로 쪼개서 3번과 5번 데이터를 수직으로 붙여라.

In [96]:
iris_rows = np.vsplit(irisdt, 150)
np.vstack([iris_rows[3], iris_rows[5]])

array([[4.6, 3.1, 1.5, 0.2],
       [5.4, 3.9, 1.7, 0.4]])

## 단항 유니버설 함수

1. sepal width(cm)의 값의 제곱근을 구하라.
2. iris 배열 전체의 값을 반올림하라.
3. petal length(cm)의 값이 숫자인지 판별하라.

In [ ]:
#1
np.sqrt(sepal_width) 

#2 
np.rint(irisdt)

#3
~np.isnan(petal_length)

## 이항 유니버설 함수
1. sepal length와 sepal width의 값의 합을 구하고, 그 값 중 가장 큰 값을 가진 인덱스를 찾아라.
2. petal length가 1.4 이상인 값을 찾아라


In [104]:
sepal_sum_result = np.add(sepal_length, sepal_width)

np.max(sepal_sum_result), np.argmax(sepal_sum_result)

(11.7, 131)

In [105]:
sepal_sum_result[131]

array([11.7])

# 카피와 뷰

첫 번째, a를 b에 선언하면 객체의 참조를 전달하므로 b에 수정사항이 그대로 a가 가리키는 배열에 영향을 미친다.

In [2]:
import numpy as np

In [4]:
a = np.arange(12)
b = a
b is a

True

In [7]:
b.shape = 3,4

In [9]:
a.shape

(3, 4)

두 번째, 뷰만 가져가서 사용하는 경우에는 뷰만 다를 뿐 실제 데이터는 동일한 곳을 참조한다. 따라서 c의 뷰를 조작하면 a에는 영향이 없지만 c가 데이터를 변형하면 a에 데이터 변형된다.

In [11]:
c = a.view()
c is a

False

In [13]:
c.shape = 2, 6 # view를 변경해도
a.shape # 실제 모양은 변경되지 않음

(3, 4)

In [16]:
c[0,4] = 1234 # view의 데이터를 수정하면 
a # 실제 데이터도 변경된다

array([[   0,    1,    2,    3],
       [1234,    5,    6,    7],
       [   8,    9,   10,   11]])

3. 딥 카피

In [17]:
d = a.copy()
d is a

False

In [18]:
d.base is a

False

In [19]:
d[0, 0] = 9999
a

array([[   0,    1,    2,    3],
       [1234,    5,    6,    7],
       [   8,    9,   10,   11]])

In [20]:
d

array([[9999,    1,    2,    3],
       [1234,    5,    6,    7],
       [   8,    9,   10,   11]])

## numpy와 python 누가 빠를까?

In [22]:
def pythonsum(n):
    a = list(range(n))
    b = list(range(n))
    c = []
    for i in range(n):
        a[i] = i ** 2
        b[i] = i ** 3
        c.append(a[i] + b[i])
    return c

pythonsum(10)

[0, 2, 12, 36, 80, 150, 252, 392, 576, 810]

In [23]:
def numpysum(n):
    a = np.arange(n) ** 2
    b = np.arange(n) ** 3
    c = a + b
    return c

numpysum(10)

array([  0,   2,  12,  36,  80, 150, 252, 392, 576, 810], dtype=int32)

In [24]:
%timeit pythonsum(100000)

55.7 ms ± 208 µs per loop (mean ± std. dev. of 7 runs, 10 loops each)


In [25]:
%timeit numpysum(100000)

297 µs ± 3.86 µs per loop (mean ± std. dev. of 7 runs, 1,000 loops each)


- 마이크로초 -> 1000000분의 1초
- 밀리초 -> 1000분의 1초

파이썬: 55700 마이크로초
넘파이: 297 마이크로초

In [28]:
print(f"넘파이는 파이썬보다 {55700/297}배 빠르다.")

넘파이는 파이썬보다 187.54208754208753배 빠르다.
