# 데이터 분석 환경 설정과 넘파이 입문

## sckit-learn, 머신러닝 패키지 버전 설치하기
아나콘다 프롬프트에서 설치를 진행해야 한다. !를 제외한 명령어를 실행하면 된다.

In [9]:
!pip install scikit-learn==1.0.2

In [10]:
!conda install py-xgboost==1.5.0

Solving environment: ...working... done

# All requested packages already installed.

Retrieving notices: ...working... done


In [11]:
!conda install -c conda-forge lightgbm==3.3.2

^C


설치된 라이브러리의 버전을 확인한다.

In [6]:
import sklearn

sklearn.__version__

'1.0.2'

In [7]:
import xgboost

xgboost.__version__

C:\Users\isc03\anaconda3\lib\site-packages\xgboost\compat.py:36: FutureWarning: pandas.Int64Index is deprecated and will be removed from pandas in a future version. Use pandas.Index with the appropriate dtype instead.
  from pandas import MultiIndex, Int64Index


'1.5.0'

In [8]:
import lightgbm

lightgbm.__version__

ModuleNotFoundError: No module named 'lightgbm'

# 넘파이
## 넘파이 배열 생성하기
numpy는 아나콘다 설치 시 기본으로 설치되어 있다.

In [13]:
import numpy as np # 별칭을 사용해서 임포트한다.

np의 기능을 활용해 배열을 생성한다.

In [15]:
arr0 = np.arange(0,10) # 파이썬의 range 와 기능이 유사하다.
arr0

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

arr0의 인덱스를 사용하면 데이터를 각각 추출해서 확인할 수 있다.

In [16]:
arr0[0]

0

In [17]:
arr0[-1]

9

In [18]:
arr0[5:7]

array([5, 6])

shape를 확인하면 현재 리스트가 어떤 모양으로 구성되었는지 확인할 수 있다.

In [20]:
arr0.shape # 행렬의 모양을 설명한다.

(10,)

기본 파이썬 리스트를 사용해서 ndarray을 생성할 수 있다.

In [23]:
# 리스트 생성
list0 = [1, 2, 3, 4, 5]
arr1 = np.array(list0) # 리스트를 ndarray로 변환해서 반환
arr1

array([1, 2, 3, 4, 5])

각 요소에 담은 데이터 형을 출력해보자.

In [27]:
arr1.dtype # 현재는 기본 설정으로 int32가 구성된다.

dtype('int32')

데이터 타입을 정하고 싶은 경우에는 int32나 int64와 같이 데이터형을 정해주는 것이 좋다.

In [29]:
arr2 = np.array(list0, dtype="int64")
arr2.dtype

dtype('int64')

## 2차원 배열 만들기

In [30]:
list1 = [[1, 2],
         [3, 4]] # 2차원 데이터 2x2

# 2차원 ndarray 구성하기
arr1 = np.array(list1)
arr1

array([[1, 2],
       [3, 4]])

In [31]:
arr1.shape

(2, 2)

2차원 배열도 인덱싱이 가능하다.

In [33]:
arr1[0] # 0번째 행을 가져옴

array([1, 2])

In [34]:
arr1[0][0] # 0번쨰 행에서 0번째 열을 가져온다.

1

In [35]:
arr1[0][1] # 0번쨰 행에서 1번째 열을 가져온다.

2

In [36]:
arr1[1][0] # 1번째 행에서 0번째 열을 가져온다.

3

In [37]:
arr1[1][1] # 1번째 행에서 1번째 열을 가져온다.

4

배열의 연산

In [38]:
arr1 + 2 # +2는 각각의 요소에 분배되어 연산된다.

array([[3, 4],
       [5, 6]])

In [39]:
arr1 * 2 # *2는 각각의 요소에 분배되어 연산된다.

array([[2, 4],
       [6, 8]])